# Generated by Django 4.1 on 2022-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=200)),
                ('product_cost', models.IntegerField(max_length=5)),
                ('manu_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
