# Generated by Django 4.1 on 2022-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='product_cost',
            field=models.IntegerField(),
        ),
    ]
