# Generated by Django 4.1 on 2022-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_information_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='product_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='products/'),
        ),
    ]
