# Generated by Django 4.1 on 2022-10-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_information_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
