# Generated by Django 4.1 on 2022-10-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_information_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='product_description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='information',
            name='product_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='information',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
