# Generated by Django 4.1 on 2022-10-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_admins_alter_information_product_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.AddField(
            model_name='information',
            name='product_category',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
