# Generated by Django 4.1 on 2022-10-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_delete_admins_information_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='product_image',
        ),
    ]
